export enum domainEnum {
  ALL = 'ALL',
  ALERT = 'ALERT',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  BANK_ACCOUNT_ADMIN = 'BANK_ACCOUNT_ADMIN',
  COMMENT = 'COMMENT',
  COMMISSION = 'COMMISSION',
  COMMISSION_AGENT = 'COMMISSION_AGENT',
  COMMISSION_CAMPAIGN = 'COMMISSION_CAMPAIGN',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  COMPANY_BACKOFFICE = 'COMPANY_BACKOFFICE',
  COMPANY_CLIENT = 'COMPANY_CLIENT',
  CONFIGURATION = 'CONFIGURATION',
  DOCUMENT = 'DOCUMENT',
  ECONOMIC_GROUP = 'ECONOMIC_GROUP',
  ECONOMIC_GROUP_ADMIN = 'ECONOMIC_GROUP_ADMIN',
  ECONOMIC_GROUP_LIMIT = 'ECONOMIC_GROUP_LIMIT',
  EXTERNAL_INFO = 'EXTERNAL_INFO',
  IDENTIFICATION = 'IDENTIFICATION',
  OFFER = 'OFFER',
  ORGANIZATION = 'ORGANIZATION',
  PROPERTY = 'PROPERTY',
  QUESTION = 'QUESTION',
  QUESTION_ANSWER = 'QUESTION_ANSWER',
  ROLES = 'ROLES',
  SCHEDULED_TASK = 'SCHEDULED_TASK',
  STORAGE = 'STORAGE',
  USER = 'USER',
  USER_ADMIN = 'USER_ADMIN',
  WHATSAPP = 'WHATSAPP',
  // for delete
  AUTHORIZATION = 'AUTHORIZATION',
  OFFER_CLIENT = 'OFFER_CLIENT',
  OFFER_INSTALLMENT = 'OFFER_INSTALLMENT',
  REPUTATION = 'REPUTATION',
}

export enum operationAreaRoleEnum {
  BACKOFFICE = 'BACKOFFICE',
  CLIENT = 'CLIENT',
  ENTREPRENEUR = 'ENTREPRENEUR',
  PARTNER = 'PARTNER',
  SECURITY = 'SECURITY',
  CURATOR = 'CURATOR'
}

export enum permissionAuthorityTOEnum {
  READ = 'READ',
  WRITE = 'WRITE',
  MODIFY = 'MODIFY',
  DELETE = 'DELETE',
}

export enum featureSaasPkgEnum {
  BigData = 'BigData',
  SCR = 'SCR',
  SPED = 'SPED',
  SPED_PDF = 'SPED_PDF',
  IRPF = 'IRPF',
  Digital_Certificate = 'Digital_Certificate',
  METHOD_K = 'METHOD_K'
}
