name: Docker Image CI with Multi-Stage Build

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Login DockerHub
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - name: Build the Docker image
              run: docker build -t techzilla-web .
            - name: Create tag for build
              run: docker tag techzilla-web:latest armoreno2626/techzilla-web:latest
            - name: Push the Docker image
              run: docker push armoreno2626/techzilla-web:latest

    deploy:  # Separate deploy job (CD)
        runs-on: ubuntu-latest
        needs: build  # Waits for build job to finish
        steps:
            - uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_PRIVATE_KEY }}
                  script: |  # Script to be executed on EC2
                      docker stop techzilla-web || true
                      docker rm techzilla-web || true
                      docker pull armoreno2626/techzilla-web:latest
                      docker run -d -p 80:80 --name techzilla-web armoreno2626/techzilla-web:latest
