name: Docker Image CI with Multi-Stage Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: armoreno2626/techzilla-web:latest
        file: techzilla-web/Dockerfile  # Path to your Dockerfile

  deploy:  # Separate deploy job (CD)
    runs-on: ubuntu-latest
    needs: build  # Waits for build job to finish
    steps:
    - uses: appleboy/ssh-action@v3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |  # Script to be executed on EC2
          docker stop techzilla-web || true
          docker rm techzilla-web || true
          docker pull armoreno2626/techzilla-web:latest
          docker run -d -p 80:80 --name techzilla-web armoreno2626/techzilla-web:latest
