name: Docker Image CI with Multi-Stage Build

on:
    push:
        branches:
            - main
            - develop

jobs:
    # Trabajo común que se ejecuta para ambas ramas
    common_tasks:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'

            - name: Get current date and time
              id: datetime
              run: echo "::set-output name=datetime::$(date +'%Y-%m-%d %H:%M:%S')"

            - name: Send custom message
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                      The deployment of the web application began at ${{ steps.datetime.outputs.datetime }}.

    # Trabajo para la rama develop
    job_for_develop:
        needs: common_tasks
        if: github.ref == 'refs/heads/develop'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to DockerHub
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            - name: Build the Docker image
              run: docker build -t techmemo-web .

            - name: Create tag for build
              run: docker tag techmemo-web:latest armoreno2626/techmemo-web:latest

            - name: Push the Docker image
              run: docker push armoreno2626/techmemo-web:latest

            - name: Send custom message

#    # Trabajo para la rama main
#    job_for_main:
#        needs: common_tasks
#        if: github.ref == 'refs/heads/main'
#        runs-on: ubuntu-latest
#        steps:
#            - name: Checkout code
#              uses: actions/checkout@v3
#
#            - name: Build the Angular project
#              uses: actions/setup-node@v3
#              with:
#                  node-version: '20'
#            - run: npm install
#            - run: npm run build

    # Trabajo de despliegue para ambas ramas
    deploy:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
#        needs:
#            - job_for_main
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build the Angular project
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
            -   run: npm install
            -   run: npm run build

            # Configurar credenciales de AWS para la implementación en S3
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            # Eliminar el contenido existente del bucket S3
            - name: Empty S3 bucket
              run: aws s3 rm s3://techmemo-app --recursive

            # Copiar archivos compilados a S3
            - name: Sync to S3
              run: aws s3 sync ./dist/techmemo-web s3://techmemo-app

            - name: Send custom message
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_TO }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                      The deployment of the web application finished at ${{ steps.datetime.outputs.datetime }}.
                      For download docker image use docker pull armoreno2626/techmemo-web:latest
