name: Docker Image CI with Multi-Stage Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t techzilla-web .

      - name: Create tag for build
        run: docker tag techzilla-web:latest armoreno2626/techzilla-web:latest

      - name: Push the Docker image
        run: docker push armoreno2626/techzilla-web:latest

  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The ${{ github.event_name }} event triggered final step.
            echo This event is a pull request that had an assignee removed.


#    deploy:  # Separate deploy job (CD)
#        runs-on: ubuntu-latest
#        needs: build  # Waits for build job to finish
#        steps:
#            - uses: appleboy/ssh-action@master
#              with:
#                  host: ${{ secrets.EC2_HOST }}
#                  username: ${{ secrets.EC2_USERNAME }}
#                  key: ${{ secrets.EC2_PRIVATE_KEY }}
#                  script: |  # Script to be executed on EC2
#                      sudo yum update -y
#                      sudo yum install git -y
#                      sudo yum install docker -y
#                      sudo groupadd docker
#                      sudo usermod -a -G docker ${{ secrets.EC2_USERNAME }}
#                      id ${{ secrets.EC2_USERNAME }}
#                      sudo newgrp docker
#
#                      #Ativar docker
#                      sudo systemctl enable docker.service
#                      sudo systemctl start docker.service
#                      docker stop techzilla-web || true
#                      docker rm techzilla-web || true
#                      docker pull ${{ secrets.DOCKER_USERNAME }}/techzilla-web:latest
#                      docker run -d -p 80:80 --name techzilla-web ${{ secrets.DOCKER_USERNAME }}/techzilla-web:latest
